### ISSUE TITLE
Not available on Docker Hub anymore

### ISSUE THREAD

**Issue by pvdlg** [nmarus/docker-gitbox#2]
Since recently the image is not available on Docker Hub anymore: https://hub.docker.com/r/nmarus/docker-gitbox/

Is it intentional?

**Comment by matthew-hickok** [comment]
@pvdlg it looks like you published the image on Docker Hub now? Are you using the same Dockerfile and script?

**Comment by pvdlg** [comment]
I published it as a workaround. Yes I use the same Dockerfile and script.
If you publish it again, I'll remove mine.

**Comment by matthew-hickok** [comment]
I'm not the owner of this repo -- I just came here because I noticed the same thing :)

**Comment by pvdlg** [comment]
> I'm not the owner of this repo -- I just came here because I noticed the same thing :)

Ah sorry, for some reason I though you were :)

**Comment by nmarus** [comment]
Removed from Docker Hub as I am no longer actively maintaining this repo. Feel free to fork and publish to docker hub.
